# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类别名称')),
                ('isIncome', models.BooleanField(choices=[(True, '收入'), (False, '支出')], verbose_name='是否收入')),
                ('p_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='jizhang.Category', verbose_name='父类名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='金额')),
                ('pub_date', models.DateField(verbose_name='日期')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='注释')),
                ('category', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jizhang.Category', verbose_name='分类')),
            ],
        ),
    ]
