# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0003_auto_20170529_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='类别名称'),
        ),
    ]
