# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0004_auto_20170529_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-pub_date']},
        ),
    ]
